services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "1433:1433"
  fullcart.api:
    image: fullcart.api
    build:
      context: .
      dockerfile: FullCart.API/Dockerfile
    restart: on-failure
    depends_on:
      - db
    links:
      - db
