services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "5433:1433"
    networks:
      - proxybackend
  scallingbackground.service.one:
    image: scallingbackground.one
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Service_Name=scalling.service.one
    ports:
      - 8000:8080
      - 8001:443
    build:
      context: .
      dockerfile: ScallingBackground/Dockerfile
    restart: on-failure
    depends_on:
      - db
    networks:
      - proxybackend
  scallingbackground.service.two:
    image: scallingbackground.two
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Service_Name=scalling.service.two
    ports:
      - 9000:8080
      - 9001:443
    build:
      context: .
      dockerfile: ScallingBackground/Dockerfile
    restart: on-failure
    depends_on:
      - db
    networks:
      - proxybackend
  #  fullcart.api:
  #    image: fullcart.api
  #    environment:
  #      - ASPNETCORE_ENVIRONMENT=Development
  #    ports:
  #    - 8000:8080
  #    - 8001:443
  #    build:
  #      context: .
  #      dockerfile: FullCart.API/Dockerfile
  #    restart: on-failure
  #    depends_on:
  #      - db
  #    networks:
  #      - proxybackend
  #fullcart.api2:
  #  image: fullcart.api2
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #  - 9000:8080
  #  - 9001:443
  #  build:
  #    context: .
  #    dockerfile: FullCart.API/Dockerfile
  #  restart: on-failure
  #  depends_on:
  #    - db
  #  networks:
  #    - proxybackend
networks:
  proxybackend:
    name: proxybackend
    driver: bridge
